# Generated by Django 2.2.3 on 2020-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('settlement_id', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deposit_date', models.DateField()),
                ('total_amount', models.CharField(max_length=255)),
                ('total_num_transactions', models.IntegerField()),
                ('report_id', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('settlement_id', 'report_id')},
            },
        ),
    ]
